"""Utility functions and classes for logits processor tests."""

import torch
from vllm import SamplingParams
from vllm.config import VllmConfig
from vllm.v1.core.sched.output import CachedRequestData, NewRequestData, SchedulerOutput
from vllm.v1.request import Request
from vllm.v1.sample.logits_processor import BatchUpdate, LogitsProcessor, MoveDirectionality

from sendnn_inference.v1.sample.spyre_logits_processor import (
    LogitProcessorWrapper,
)


class DummyLogitsProcessor(LogitsProcessor):
    """A simple dummy logits processor for testing registration."""

    def __init__(self, vllm_config: VllmConfig, device: torch.device, is_pin_memory: bool):
        # Required to register LogitsProcessor
        pass

    def is_argmax_invariant(self) -> bool:
        return False

    def update_state(self, batch_update: BatchUpdate | None):
        # Required to register LogitsProcessor
        pass

    def apply(self, logits: torch.Tensor) -> torch.Tensor:
        return logits


class SpyLogitsProcessor(LogitsProcessor):
    """
    A logits processor that collects generated tokens for verification.

    This processor tracks the state of requests and collects the tokens
    generated by each request, storing them in the provided spy_outputs dict.
    """

    def __init__(
        self,
        vllm_config: VllmConfig,
        device: torch.device,
        is_pin_memory: bool,
        spy_outputs: dict[int, list[int]],
    ):
        self.req_info: dict[int, SamplingParams] = {}
        # Saved state for paused requests, keyed by req_id.
        self._paused_info: dict[str, SamplingParams] = {}
        self.spy_outputs = spy_outputs

    def is_argmax_invariant(self) -> bool:
        return False

    def update_state(self, batch_update: BatchUpdate | None):
        if not batch_update:
            return

        for index, params, _, _ in batch_update.added:
            self.req_info[index] = params
            # Use setdefault so a resume-triggered added event does not
            # reset tokens already collected before the pause.
            self.spy_outputs.setdefault(params.max_tokens, [])

        if self.req_info:
            # Process removed requests.
            for index in batch_update.removed:
                self.req_info.pop(index, None)

            # Process moved requests, unidirectional move (a->b) and swap
            # (a<->b)
            for adx, bdx, direct in batch_update.moved:
                a_val = self.req_info.pop(adx, None)
                b_val = self.req_info.pop(bdx, None)
                if a_val is not None:
                    self.req_info[bdx] = a_val
                if direct == MoveDirectionality.SWAP and b_val is not None:
                    self.req_info[adx] = b_val

    def apply(self, logits: torch.Tensor) -> torch.Tensor:
        if not self.req_info:
            return logits
        batch_size = logits.shape[0]
        for i in range(batch_size):
            params = self.req_info[i]
            token_id = logits[i].argmax(-1).reshape(-1).item()
            self.spy_outputs[params.max_tokens].append(token_id)
        return logits


class StateTrackingLogitsProcessorWrapper(LogitProcessorWrapper):
    """
    Extends LogitProcessorWrapper to track batch-level state for testing.

    This wrapper tracks all state transitions including adds, removes, pauses,
    resumes, and moves. It maintains a log of all operations and verifies that
    indices remain consecutive after each update.
    """

    def __init__(
        self,
        logit_processor: type[LogitsProcessor],
        vllm_config: VllmConfig,
        device: torch.device,
        is_pin_memory: bool,
        batch_size: int,
        state_log: list[dict],
    ):
        super().__init__(logit_processor, vllm_config, device, is_pin_memory, batch_size)
        # Map dense_index -> (req_id, token_count)
        self.active_requests: dict[int, tuple[str, int]] = {}
        # Map req_id -> (last_dense_index, token_count) for paused requests
        self.paused_requests: dict[str, tuple[int, int]] = {}
        self.step_count = 0
        self.request_counter = 0  # Counter for number of requests seen
        self.state_log = state_log

    def update_state(self, batch_update: BatchUpdate | None) -> None:
        # Call parent to handle the actual logits processor state
        super().update_state(batch_update)

        # Track our own state for testing
        if not batch_update:
            return

        self.step_count += 1
        step_info = {
            "step": self.step_count,
            "batch_size": batch_update.batch_size,
            "operations": [],
            "active_before": dict(self.active_requests),
            "paused_before": dict(self.paused_requests),
        }

        # Process added requests
        for dense_index, params, prompt_toks, output_toks in batch_update.added:
            req_id = f"req{self.request_counter}"  # Use request counter as identifier
            self.request_counter += 1
            token_count = len(output_toks)

            # Verify no overwrite - raise error immediately
            if dense_index in self.active_requests:
                old_req = self.active_requests[dense_index]
                raise AssertionError(
                    f"Overwrite detected at step {self.step_count}: "
                    f"index {dense_index} already has {old_req}, "
                    f"attempting to add {(req_id, token_count)}"
                )

            self.active_requests[dense_index] = (req_id, token_count)
            step_info["operations"].append(
                {"type": "added", "index": dense_index, "req_id": req_id, "tokens": token_count}
            )

        # Process resumed requests (restore from pause)
        if hasattr(batch_update, "resumed"):
            for dense_index, req_id in batch_update.resumed:
                if req_id in self.paused_requests:
                    old_index, token_count = self.paused_requests.pop(req_id)
                    self.active_requests[dense_index] = (req_id, token_count)
                    step_info["operations"].append(
                        {
                            "type": "resumed",
                            "index": dense_index,
                            "req_id": req_id,
                            "old_index": old_index,
                            "tokens": token_count,
                        }
                    )

        # Process paused requests (save state)
        if hasattr(batch_update, "paused"):
            for dense_index, req_id in batch_update.paused:
                if dense_index in self.active_requests:
                    req_info = self.active_requests.pop(dense_index)
                    self.paused_requests[req_id] = (dense_index, req_info[1])
                    step_info["operations"].append(
                        {
                            "type": "paused",
                            "index": dense_index,
                            "req_id": req_id,
                            "tokens": req_info[1],
                        }
                    )

        # Process finished paused requests (remove from paused state)
        if hasattr(batch_update, "finished_paused"):
            for req_id in batch_update.finished_paused:
                if req_id in self.paused_requests:
                    paused_info = self.paused_requests.pop(req_id)
                    step_info["operations"].append(
                        {
                            "type": "finished_paused",
                            "req_id": req_id,
                            "last_index": paused_info[0],
                            "tokens": paused_info[1],
                        }
                    )

        # Process removed requests
        for dense_index in batch_update.removed:
            if dense_index in self.active_requests:
                req_info = self.active_requests.pop(dense_index)
                step_info["operations"].append(
                    {
                        "type": "removed",
                        "index": dense_index,
                        "req_id": req_info[0],
                        "tokens": req_info[1],
                    }
                )

        # Process moved requests (always swaps like LogitProcessorWrapper)
        for src_idx, dst_idx, _ in batch_update.moved:
            src_req = self.active_requests.get(src_idx)
            dst_req = self.active_requests.get(dst_idx)

            # Always swap both positions (matching LogitProcessorWrapper behavior)
            if src_req:
                self.active_requests[dst_idx] = src_req
            else:
                self.active_requests.pop(dst_idx, None)
            if dst_req:
                self.active_requests[src_idx] = dst_req
            else:
                self.active_requests.pop(src_idx, None)

            step_info["operations"].append(
                {
                    "type": "moved",
                    "src": src_idx,
                    "dst": dst_idx,
                    "src_req": src_req,
                    "dst_req": dst_req,
                }
            )

        step_info["active_after"] = dict(self.active_requests)
        step_info["paused_after"] = dict(self.paused_requests)

        # Verify indices are consecutive immediately after each update
        if self.active_requests:
            indices = sorted(self.active_requests.keys())
            expected = list(range(len(indices)))
            if indices != expected:
                step_info["operations"].append(
                    {
                        "type": "ERROR_NON_CONSECUTIVE",
                        "actual_indices": indices,
                        "expected_indices": expected,
                        "message": (f"Indices are not consecutive: {indices}, expected {expected}"),
                    }
                )

        self.state_log.append(step_info)

    def apply(self, logits: torch.Tensor) -> torch.Tensor:
        # Increment token count for all active requests
        for idx in self.active_requests:
            req_id, token_count = self.active_requests[idx]
            self.active_requests[idx] = (req_id, token_count + 1)
        return super().apply(logits)


def make_request(req_id: str, prompt_len: int, max_tokens: int) -> Request:
    """Create a Request object for testing."""
    return Request(
        request_id=req_id,
        prompt_token_ids=[42] * prompt_len,
        sampling_params=SamplingParams(max_tokens=max_tokens, temperature=0),
        pooling_params=None,
    )


def make_new_req_data(req_id: str, prompt_len: int, max_tokens: int) -> NewRequestData:
    """Create NewRequestData for testing."""
    req = make_request(req_id, prompt_len, max_tokens)
    block_ids = list(range(1, (prompt_len + 63) // 64 + 1))
    return NewRequestData.from_request(req, block_ids=(block_ids,))


def make_cached_req_data(req_states: dict[str, tuple[int, list[int]]]) -> CachedRequestData:
    """Create CachedRequestData for testing."""
    cached = CachedRequestData.make_empty()
    cached.req_ids = list(req_states.keys())
    cached.num_computed_tokens = [state[0] for state in req_states.values()]
    cached.new_block_ids = [None for _ in req_states]  # Simplified for test
    return cached


def execute_step(
    runner,
    processor: StateTrackingLogitsProcessorWrapper,
    new_reqs: list[tuple[str, int, int]] | None = None,
    cached_reqs: list[tuple[str, int]] | None = None,
    num_scheduled_tokens: dict[str, int] | None = None,
    finished_req_ids: set[str] | None = None,
    expected_active: dict[int, tuple[str, int]] | None = None,
    expected_paused: set[str] | None = None,
    actual_outputs: dict[str, list[int]] | None = None,
):
    """
    Execute a scheduler step and verify the resulting state.

    Args:
        runner: The model runner to execute the step on
        processor: The state tracking processor to verify
        new_reqs: List of new requests as (req_id, prompt_len, max_tokens)
        cached_reqs: List of cached requests as (req_id, num_computed_tokens)
        num_scheduled_tokens: Dict mapping req_id to number of tokens scheduled
        finished_req_ids: Set of request IDs that finished in this step
        expected_active: Expected active requests mapping dense_index to (req_id, token_count)
        expected_paused: Expected set of paused request IDs
        actual_outputs: Optional dict to collect generated tokens, keyed by request_id
    """
    # Build new request data
    scheduled_new_reqs = []
    if new_reqs:
        for req_id, prompt_len, max_tokens in new_reqs:
            scheduled_new_reqs.append(make_new_req_data(req_id, prompt_len, max_tokens))

    # Build cached request data
    if cached_reqs:
        req_states = {req_id: (num_computed, []) for req_id, num_computed in cached_reqs}
        scheduled_cached_reqs = make_cached_req_data(req_states)
    else:
        scheduled_cached_reqs = CachedRequestData.make_empty()

    # Build scheduler output
    sched_out = SchedulerOutput(
        scheduled_new_reqs=scheduled_new_reqs,
        scheduled_cached_reqs=scheduled_cached_reqs,
        num_scheduled_tokens=num_scheduled_tokens or {},
        total_num_scheduled_tokens=sum((num_scheduled_tokens or {}).values()),
        finished_req_ids=finished_req_ids or set(),
        kv_connector_metadata=None,
        scheduled_spec_decode_tokens={},
        scheduled_encoder_inputs={},
        num_common_prefix_blocks=[],
        free_encoder_mm_hashes=[],
    )

    # Execute the step
    output = runner.execute_model(sched_out)

    # Collect generated tokens into actual_outputs if provided
    if actual_outputs is not None and output.sampled_token_ids:
        # Map dense indices to request IDs and collect tokens
        for dense_idx, token_ids in enumerate(output.sampled_token_ids):
            if dense_idx in processor.active_requests:
                req_id, token_count = processor.active_requests[dense_idx]
                # Extract the actual token (first element of token_ids list)
                actual_token = token_ids[0] if isinstance(token_ids, list) else token_ids

                # Initialize list for this request if not exists
                if req_id not in actual_outputs:
                    actual_outputs[req_id] = []

                # Append the generated token
                actual_outputs[req_id].append(actual_token)

    # Verify expected state if provided
    if expected_active is not None:
        for dense_idx, (expected_req_id, expected_token_count) in expected_active.items():
            assert dense_idx in processor.active_requests, (
                f"Expected index {dense_idx} to be active"
            )
            actual_req_id, actual_token_count = processor.active_requests[dense_idx]
            assert actual_req_id == expected_req_id, (
                f"Expected {expected_req_id} at index {dense_idx}, got {actual_req_id}"
            )
            assert actual_token_count == expected_token_count, (
                f"Expected {expected_token_count} tokens for {expected_req_id} "
                f"at index {dense_idx}, got {actual_token_count}"
            )
        assert len(processor.active_requests) == len(expected_active), (
            f"Expected {len(expected_active)} active requests, got {len(processor.active_requests)}"
        )

    if expected_paused is not None:
        actual_paused = set(processor.paused_requests.keys())
        assert actual_paused == expected_paused, (
            f"Expected paused requests {expected_paused}, got {actual_paused}"
        )

    return output
