"""Compare graphs generated by SenDNN-Inference vs AFTU.

This test compares computation graphs generated by SenDNN-Inference against those
generated by AFTU (AIU FMS Testing Utils) to ensure compatibility.

Graph directories are created in pytest's temp directory and automatically
cleaned up after 3 test sessions. On test failure, directories are preserved
for debugging:
- aftu_graphs_*: AFTU generated graphs
- vllm_graphs_*: vLLM generated graphs
Each directory contains a normalized_graphs/ subdirectory for easier comparison.

Run: python -m pytest tests/aftu/test_compare_graphs.py
"""

import os
import sys

import pytest
from graph_compare_utils import (
    collect_graph_files,
    compare_graphs,
    get_model_path,
    run_inference_py_and_get_graphs,
    save_normalized_graphs,
)
from spyre_util import ModelInfo, environ_checkpoint, patch_environment
from vllm import LLM


@pytest.mark.spyre
@pytest.mark.chunked_prefill
def test_compare_graphs_chunked_prefill(
    model: ModelInfo,
    max_num_seqs: int,
    max_model_len: int,
    monkeypatch: pytest.MonkeyPatch,
    tmp_path_factory: pytest.TempPathFactory,
):
    """Test if the graphs generated by sendnn-inference matches with the ones by
    AFTU with chunked prefill enabled

    Graph directories are preserved on failure for debugging.
    """
    model_path = get_model_path(model)

    chunk_size = 128

    # fmt: off
    inference_py_args = [
        sys.executable, "-m", "aiu_fms_testing_utils.scripts.inference",
        "--architecture", "hf_pretrained",
        "--model_path", model_path,
        "--tokenizer", model_path,
        "--unfuse_weights",
        "--device_type", "aiu",
        "--compile",
        "--cast_bf16_to_fp16",
        "--compile_dynamic",
        "--min_pad_length", "64",
        "--max_new_tokens", "5",
        "--batch_size", str(max_num_seqs),
        "--compile_dynamic_sendnn",
        "--prefill_chunk_size", str(chunk_size),
    ]
    # fmt: on

    if not model.is_quantized:
        inference_py_args += ["--default_dtype", "fp16"]
        inference_py_args += ["--attention_type", "paged"]
    else:
        inference_py_args += ["--attention_type", "paged_fp8"]

    extra_env = {
        "VLLM_DT_MAX_CONTEXT_LEN": str(max_model_len),
        "VLLM_DT_MAX_BATCH_SIZE": str(max_num_seqs),
        "VLLM_DT_MAX_BATCH_TKV_LIMIT": str(1024 * 128),
        "VLLM_DT_CHUNK_LEN": str(chunk_size),
    }

    # Create temp directories using pytest's tmp_path_factory
    aftu_tmpdir = str(tmp_path_factory.mktemp("aftu_graphs"))
    aftu_graphs, _ = run_inference_py_and_get_graphs(
        inference_py_args, extra_env, tmpdir=aftu_tmpdir
    )

    assert len(aftu_graphs) > 0, "No AFTU graphs generated"

    # Save normalized graphs for debugging
    aftu_normalized_dir = save_normalized_graphs(aftu_graphs, aftu_tmpdir)

    # vLLM

    monkeypatch.setenv("DEE_DUMP_GRAPHS", "vllm_cb_cp")
    # Disable cache to produce the graphs
    monkeypatch.setenv("TORCH_SENDNN_CACHE_ENABLE", "0")

    # NB: On pytorch 2.10 currently the eager and sendnn_compile_only backends do not work for
    # quantized models.
    backend = "sendnn" if model.is_quantized else "sendnn_compile_only"
    patch_environment(
        backend=backend,
        monkeypatch=monkeypatch,
    )

    # NB: We need AFTU and sendnn-inference to have the same number of paged
    # attention blocks for the graph comparison.
    #
    # sendnn-inference adds 1 block to the full batch count for the padding block and
    # rounds up to a multiple of the batch size (see get_total_spyre_blocks in
    # spyre_model_runner.py).
    #
    # Adjusting the context length for vLLM by the block size counters the
    # padding block adjustment for alignment with AFTU
    adjusted_max_model_len = max_model_len - 64
    original_cwd = os.getcwd()
    vllm_tmpdir = str(tmp_path_factory.mktemp("vllm_graphs"))

    try:
        os.chdir(vllm_tmpdir)

        # Load the model to generate graphs
        with environ_checkpoint():
            LLM(
                model=model.name,
                revision=model.revision,
                max_model_len=adjusted_max_model_len,
                tensor_parallel_size=1,
                max_num_batched_tokens=chunk_size,
                max_num_seqs=max_num_seqs,
            )

        vllm_graphs = collect_graph_files(vllm_tmpdir)
        assert len(vllm_graphs) > 0, "No vLLM graphs generated"

        # Save normalized graphs for debugging
        vllm_normalized_dir = save_normalized_graphs(vllm_graphs, vllm_tmpdir)

    finally:
        os.chdir(original_cwd)

    # Compare graphs
    graphs_match, differences = compare_graphs(vllm_graphs, aftu_graphs)

    if not graphs_match:
        # Build detailed error message
        missing_in_vllm = set(aftu_graphs.keys()) - set(vllm_graphs.keys())
        missing_in_aftu = set(vllm_graphs.keys()) - set(aftu_graphs.keys())

        error_msg = [
            "\nGraph comparison failed!",
            f"AFTU graphs: {aftu_tmpdir}",
            f"  Normalized: {aftu_normalized_dir}",
            f"vLLM graphs: {vllm_tmpdir}",
            f"  Normalized: {vllm_normalized_dir}",
            f"\nAFTU graph count: {len(aftu_graphs)}",
            f"vLLM graph count: {len(vllm_graphs)}",
        ]

        if missing_in_vllm:
            error_msg.append(f"\nMissing in vLLM: {sorted(missing_in_vllm)}")
        if missing_in_aftu:
            error_msg.append(f"Missing in AFTU: {sorted(missing_in_aftu)}")

        if differences:
            error_msg.append("\nDifferences:")
            error_msg.extend(differences)

        error_msg.append(f"\nCompare with: diff -ur {aftu_normalized_dir} {vllm_normalized_dir}")

        pytest.fail("\n".join(error_msg))
